### ISSUE TITLE
关于时区的一个问题

### ISSUE THREAD

**Issue by laomocode** [panjunwen/Valine-Admin#63]
我是在Leancloud的国际版来部署这个的，但是发现时间用的是UTC时间，请问，能不能在以后的新版本加入时区设置的功能呢？

**Comment by leafjame** [comment]
我也是用的国际版，比如定时任务，减八个小时就ok了😁
要么设置成`0 0/30 0-23 * * ?`和`0 0 0 * * ?`

**Comment by shanlanCoding** [comment]
请问国际版是不是不会强制休眠？

**Comment by leafjame** [comment]
> 眠

免费版本都一样，有6小时休眠

**Comment by shanlanCoding** [comment]
> > 眠
> 
> 免费版本都一样，有6小时休眠

那为什么用国际版呢？

**Comment by leafjame** [comment]
> 那为什么用国际版呢？

参考：[这篇文章](https://www.liaofuzhan.com/posts/554801533.html)

**Comment by shanlanCoding** [comment]
谢谢你的解答。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Stardust"<notifications@github.com&gt;; 
发送时间: 2019年12月13日(星期五) 下午2:48
收件人: "DesertsP/Valine-Admin"<Valine-Admin@noreply.github.com&gt;; 
抄送: "两载"<291637732@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [DesertsP/Valine-Admin] 关于时区的一个问题 (#63)



 
那为什么用国际版呢？
  
参考：这篇文章
 
&mdash;

**Comment by pengruifei** [comment]
- 由于CRON 表达式采用的是UTC+0时区，又考虑到Leancloud体验版有6个小时的强制休眠时间，建议将自动唤醒的Cron表达式改为

```
0 */25 0-15,23 * * ? 
```

表示从北京时间7点00开始唤醒，到晚上11点50最后一次唤醒

- 相应的将补发邮件的定时任务Cron表达式改为
```
0 10 23 * * ?  
```
对应中国时间早上7：10补发邮件

**Comment by aixiu** [comment]
现在不是时区的问题，而是因流控原因,通过定时任务唤醒体验版实例失败,建议升级至标准版云引擎实例避免休眠。看来要想其它办法了。

**Comment by pengruifei** [comment]
放弃leancloud的定时任务，利用github actions中的workflow定时执行命令访问leancloud的web域名，即可解决leancloud平台因为流控原因无法激活定时唤醒任务的问题。

workflow yml文件中的代码如下

```
name: 'wake comment system'
on:
  push:
  schedule:
    - cron: '7,33,53 0-15,23 * * *'
    
jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: 'Checkout codes' # 步骤一，获取仓库代码
        uses: actions/checkout@v1
      - name: 'Run visiturl.sh' # 步骤二，执行sh命令文件
        run: bash visiturl.sh # 运行命令。（注意，运行目录是仓库根目录）
```

visiturl.sh放在github pages仓库的根目录即可，代码如下

```
#!/usr/bin/env sh
set -e
curl "改为你的web域名"
```

**Comment by 0x020B** [comment]
我把楼上的配置改了一下，更短，还可以隐藏域名
```
name: 'wake comment system'
on:
  push:
  schedule:
    - cron: '7,33,53 0-15,23 * * *'
    
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sLo /dev/null ${{ secrets.DOMAIN }}
```
仓库->settings->secrets->actions->New repository secret
Name: DOMAIN
Value: 你的web域名
